global using CommunityToolkit.Maui;
global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Maui.Core;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using NeospectraMauiDemo.Models;
global using NeospectraMauiDemo.Model;
global using SensingKit.Core.Model;
global using NeospectraMauiDemo.Helpers;

global using NeospectraMauiDemo.Pages;
global using NeospectraMauiDemo.Views;
global using NeospectraMauiDemo.Services;
global using NeospectraMauiDemo.Driver;
global using NeospectraMauiDemo.Uuids;
global using NeospectraMauiDemo.ViewModels;
global using Microsoft.Maui.ApplicationModel;
global using Plugin.BLE;
global using Plugin.BLE.Abstractions;
global using Plugin.BLE.Abstractions.Contracts;
global using Plugin.BLE.Abstractions.EventArgs;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using IAdapter = Plugin.BLE.Abstractions.Contracts.IAdapter;
